### ISSUE TITLE
Network configuration GUI

### ISSUE THREAD

**Issue by mojodna** [posm/posm#11]
The SSID and AP password should be configurable by administrators in the field; this means that we need to expose this functionality via a web UI. Ideally, one of the captive portal options will include this (and/or we'll need to crib from OpenWRT, DD-WRT, etc.).
- [x] set SSID `ssid2="{{posm_ssid}}"` in `/etc/hostapd.conf`
- [x] set AP password - `wpa_passphrase={{posm_wpa_passphrase}}` in `/etc/hostapd.conf`
- [x] set hostname - `/etc/hostname` / `hostname` / `hostname` upstart service
- [x] bridge / captive `/etc/network/interfaces` / `/etc/default/dnsmasq` / `/etc/dnsmasq.d/posm.conf`

**Comment by mojodna** [comment]
If this is not achievable using an off-the-shelf solution (probably the captive portal solution), let's brain dump what we know and revisit this.

**Comment by jflemer-ndp** [comment]
This one looks pretty: [RaspAP WiFi configuration portal - https://github.com/billz/raspap-webgui](https://github.com/billz/raspap-webgui).  However it does run on PHP, so we'd have to add yet another stack.

Others that are parts of bigger projects:
 * PacketFence http://packetfence.org/home.html
 * IPFire http://www.ipfire.org/

Another (PHP based) one that has a narrower set of features:
 * WiFiAdmin http://wifiadmin.sourceforge.net/ (last release 2010, last CVS commit 2 years ago)

**Comment by mojodna** [comment]
@JeremyGrosser / @jflemer-ndp is the best way to set these "on-the-fly" (change + persist configuration) by editing the config files directly or by using `iwconfig` / `iw`?

(Thinking ahead to implementing configuration changes via UI and applying them.)

**Comment by mojodna** [comment]
See https://github.com/AmericanRedCross/posm-admin/pull/8
