### ISSUE TITLE
scroll back posm-admin console

### ISSUE THREAD

**Issue by dalekunce** [posm/posm#178]
when console is running you can't really scroll back to see the output without it continuing to push you to see the latest output.

**Comment by mojodna** [comment]
Workaround that requires shell access (for when you _really_ need to figure out what was logged): console output is added to `/var/log/posm-admin.log`

**Comment by mojodna** [comment]
Done in https://github.com/posm/posm-admin-ui/commit/3ec7153603c3d21c7d871700efdbbd6580b31a25 and https://github.com/posm/posm-admin-ui/commit/0bc6ff013850f7eb859103dcb0f032e0b1ee5003
