### ISSUE TITLE
POSM Export Tool - bundle link missing

### ISSUE THREAD

**Issue by hallahan** [posm/posm#186]
When including an MBTiles in an export, the bundle doesn't get included.

For example, this bundle does not get shown:

http://export.posm.io/downloads/18d3e6f4-362b-49f9-842d-d4e8100f54ec/davis-bundle.tar.gz

for this export

http://export.posm.io/en/exports/ee35e0fa-1e8b-447a-93bc-577be53d47c0/

cc/ @mojodna

**Comment by mojodna** [comment]
I can't reproduce this. I suspect that it depends on the variety of formats that are requested (the JS result page is very brittle).
