### ISSUE TITLE
Hard-link / back up ODM outputs

### ISSUE THREAD

**Issue by mojodna** [posm/posm#226]
If they're dropped into `/opt/data/aerial-imagery` it's possible that they could be deleted by people accessing the file share. That may be desirable, but we should make sure that we keep copies around elsewhere just in case.

**Comment by mojodna** [comment]
Done in https://github.com/posm/posm-admin/commit/955f6e35c7cb3bd879d7ad938e98fca8b5314816.

**Comment by danbjoseph** [comment]
the ODM outputs are stored twice? this could result in eating up a lot of space (a bigger deal on local hardware then a cloud setting)?

**Comment by mojodna** [comment]
They look like they're stored twice--that's the beauty of hard links! Each reference points to the same inode, so there's only 1 copy stored on disk. If one copy is replaced (by writing a new file, not by modifying it), they will no longer share the same inode and there will be multiple copies (of different data).

**Comment by danbjoseph** [comment]
cool, thanks for explaining.
