### ISSUE TITLE
Remove lens distortion (if present) before passing to ODM

### ISSUE THREAD

**Issue by mojodna** [posm/posm#228]
Use [CameraCalibration](https://github.com/dakotabenjamin/CameraCalibration) to generate calibration parameters from chessboards, e.g. https://github.com/mojodna/dji_fc300c

Once calibration parameters are known, use CameraCalibration to pre-process source images, e.g. https://github.com/mojodna/odm_seattle_university

@dakotabenjamin did this for me on Windows:

```
C:\Users\dmb2\PycharmProjects\CameraCalibration>python opencv_calibrate.py --debug ..\mojodna-cal\dji_fc300c\output ..\mojod
na-cal\dji_fc300c\chessboard\*.JPG
# Then I copied the output/matrix.txt and distortion.txt to the odm_seattle_university repo
C:\Users\dmb2\PycharmProjects\CameraCalibration>python undistort.py --matrix ..\mojodna-cal\odm_seattle_university\matrix.tx
t --distortion ..\mojodna-cal\odm_seattle_university\distortion.txt ..\mojodna-cal\odm_seattle_university\images\*.JPG
```

Without correction:

![odm_orthophoto](https://cloud.githubusercontent.com/assets/45/18358990/abd93b76-75ac-11e6-96f4-b1cea5593860.png)

With correction:

![odm_orthophoto](https://cloud.githubusercontent.com/assets/45/18359024/d47c2f16-75ac-11e6-913a-ea2a66845988.png)

**Comment by emilyhobson** [comment]
May not be necessary given ARC lenses (or add-on later)

**Comment by mojodna** [comment]
Distortion removal tools are packaged up here: https://hub.docker.com/r/mojodna/undistort/
