### ISSUE TITLE
Certain Windows laptops can't connect to POSM network when secured with WPA

### ISSUE THREAD

**Issue by mojodna** [posm/posm#233]
We were seeing this with Lenovos and Windows 10 (possibly 8.1).

I just spotted this with a Dell XPS 13 running Windows 10 Pro.

System times were within a minute, so that wasn't the problem.

**Comment by mojodna** [comment]
I was hopeful that installing Windows 10 Pro on the Braswell NUC would allow me to reproduce this locally, but alas, it works.

**Comment by mojodna** [comment]
The ARC Lenovos fall into this category.

@danbjoseph what's the model?

**Comment by danbjoseph** [comment]
Lenovo B40-80 (model name: 80LS)
Windows 10 Home

**Comment by mjvanderveen** [comment]
Same issue Dell XPS 13 windows 10

**Comment by mjvanderveen** [comment]
Same with MSI gs60 2qe-230nlk1507000103 on windows 10

**Comment by mojodna** [comment]
To try:

set `ieee8021x=0` in `/etc/hostapd/hostapd.conf` and reboot the POSM to see if problematic laptops are able to connect.

(from https://serverfault.com/questions/802080/windows-10-clients-cant-connect-to-hostapd)

**Comment by mojodna** [comment]
With `posm-build@master`, the ARC B40 I'm borrowing is able to connect without problems.
