### ISSUE TITLE
Add a buoy at Null Island

### ISSUE THREAD

**Issue by mojodna** [posm/posm#238]
Plus a reasonably-sized background / shape. This becomes a useful cue to determine whether imagery / points are lacking useful coordinates.

**Comment by almccon** [comment]
Would this need to be larger or smaller than the usual Null Island? https://github.com/nixta/null-island/blob/master/GeoJSON/null-island.geo.json

**Comment by mojodna** [comment]
Actually, Null Island as-is is probably about right, since it's goodly-sized at z13.

**Comment by mojodna** [comment]
I opted for an icon so it's a common size. It starts showing up at zoom 7 because that's really the first zoom where it's possible to get disoriented and not see the coast of Africa.

![image](https://cloud.githubusercontent.com/assets/45/25464877/b9502636-2ab3-11e7-9c78-f5cae9008742.png)
