### ISSUE TITLE
installation of ubuntu on a NUC

### ISSUE THREAD

**Issue by danbjoseph** [posm/posm#281]
readme needs guidance on installing ubunutu to the nuc

**Comment by dalekunce** [comment]
@emilyeros is working on the docs here:
https://hackmd.io/MYEwRsCmCMwMwFoYDNgICwCZMgQQzAFZMFCA2MySABkgE46B2EADiA==

**Comment by danbjoseph** [comment]
docs do now have an okay version of this. doc issues tracked on https://github.com/posm/docs/issues
