### ISSUE TITLE
Installing on a laptop.

### ISSUE THREAD

**Issue by johnwhelan** [posm/posm#293]
I have an elderly Dell i7 laptop lying around so I thought I'd play with POSM.  I realise that ideally it should go an a new intel NUC but that's dollars and the repurposed laptop is available and free.

The first comment was I had to switch the boot to EUFI then it picked up the USB stick.

The install seemed to work, when it rebooted I removed the USB stick before it booted.

Then it reached the stage of a POSM login: prompt at which point the documentation gave no indication what to type next.

Suggestions please.

Thanks John

**Comment by johnwhelan** [comment]
Looks like there is more documentation here 
https://github.com/posm/posm-build so I now have a root password.

It also looks as if it needs a certain amount of customizing.

John

**Comment by danbjoseph** [comment]
We're in the process of getting some fresh documentation up. Draft work is here: https://posm.github.io/posm.io/

**Comment by johnwhelan** [comment]
Thanks I can wait to play.

John
