### ISSUE TITLE
posm.io: image galleries for documentation

### ISSUE THREAD

**Issue by mojodna** [posm/posm#300]
Google Photos albums aren't embeddable, so it looks like the best option may be a Speaker Deck presentation embedded in an iframe (markup generated via https://iframely.com/embed) added to the markdown file as HTML.

**Comment by danbjoseph** [comment]
why do we need a paid service (iframely is minimum $29/month?) for the pictures in our documentation?

**Comment by mojodna** [comment]
We don't. In the case of Speaker Deck, it just creates the right markup, which doesn't involve iframely at all.

**Comment by mojodna** [comment]
Images are inlined instead and that seems to be fine.
