### ISSUE TITLE
POSM needs manual omkserver restart

### ISSUE THREAD

**Issue by emilyeros** [posm/posm#301]
POSM#2 often gets an Error 502: Bad Gateway. This happens every time I first power up the POSM, connect to it by phone or computer, and try to access OpenMapKit/omkserver. It also happens when I connect more than a few devices to the POSM or in the middle of a series of larger file downloads (over 20 MB, e.g. an OBF file or the OsmAnd app) from the POSM public file share.

The POSM has the updated wireless card. 

This began happening after I set up the file share and did the omkserver update so it can handle encryption.

Temporary fix: SSH into POSM, run `service omk-server restart`

Screenshot of error message upon first connecting to POSM:

<img width="1285" alt="screen shot 2017-06-06 at 6 52 40 pm" src="https://user-images.githubusercontent.com/9657971/26841606-51fcf2f0-4aea-11e7-81d1-0bd2f6c874d8.png">

**Comment by mojodna** [comment]
Probably fixed by https://github.com/posm/posm-build/commit/c8c7ffc02827e3a7515c4479992de64aac698a37
