### ISSUE TITLE
Run dnsmasq in forwarding mode in the cloud

### ISSUE THREAD

**Issue by mojodna** [posm/posm#305]
This will allow the `--dns` args in Docker-related upstart scripts to be left as-is, as they tell containers to use the DNS server running locally (or not, since `dnsmasq` is part of `wifi` and not deployed when used in the cloud).

Symptom (`omk-server`):

```
Error: getaddrinfo EAI_AGAIN uganda-omk.hotosm.org:80
    at Object.exports._errnoException (util.js:1018:11)
    at errnoException (dns.js:33:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
```

Workaround: delete `--dns` args (e.g., https://github.com/posm/posm-build/blob/3da2927/kickstart/etc/omk-server.upstart#L13) in upstart configs (`/etc/init/*.conf`).

**Comment by husnimubarok** [comment]
I comment out the --dns part and re-run the bootstrap.sh and omk gives me 503 bad gateway. I checked the docker stats, no container running. and upstart logs from omk-server lgives me ""docker run" requires at least 1 argument(s)". Is there any step I missed in my setup?

**Comment by husnimubarok** [comment]
502 bad gateway issue solved, OpenMapKitServer pages now accesible. the container seems working. but the symptom was still there.

**Comment by mojodna** [comment]
Alternately, replace `--dns` with `--add-host $(jq .posm_fqdn /etc/posm.json):$(<POSM IP>)` to avoid running another service while maintaining compatibility with both cloud + physical devices.
