### ISSUE TITLE
formList broken on Collect 1.11.x ?

### ISSUE THREAD

**Issue by danbjoseph** [posm/posm#318]
on v1.10.2 it works to Get Blank Form
on v1.11.1 (Nexus 5 and Moto X4) get a 
```
Form listing failed: http://posm.io/formList
responded with: Not Found (404).
```

**Comment by mojodna** [comment]
Stupid question: are the phones running v1.11.1 connected to the right AP?

What does `curl http://posm.io/formList` return when connected to POSM?

**Comment by danbjoseph** [comment]
the phones running 1.11.1 were showing in the wifi settings that they were connected to the posm. unless maybe they're defaulting to phone network data... AND yep. that's the issue. gotta turn off cell data and then it works.

also...
```
➜  ~ curl http://posm.io/formList
<?xml version="1.0" encoding="UTF-8"?>
<xforms xmlns="http://openrosa.org/xforms/xformsList">
  <xform>
    <name>WorkshopEvaluation_v01</name>
    <formID>WorkshopEvaluation_v01</formID>
    <hash>md5:841463dc1b4b22968a33cc1633334ec2</hash>
    <downloadUrl>http://posm.io/omk/data/forms/WorkshopEvaluation_v01.xml</downloadUrl>
  </xform>
</xforms>% 
```
