### ISSUE TITLE
POSM imagery API has a 256MB limit on uploads

### ISSUE THREAD

**Issue by mojodna** [posm/posm#325]
This should be changeable by modifying `nginx-posm.conf`, per https://github.com/posm/docs/issues/4

**Comment by danbjoseph** [comment]
**Rudo**
Ah, yeah i just tried a larger one and that didn't work. But -- it led me to figure out something with Field Papers. nothing appears when i load an endpt, but when i zoom out 3 times, i see the image show up towards the south. So it just doesn't focus on the loaded image (which hopefully can be fixed)
but at least we know that the images are rendering in FP

**Seth**
Ah, great
(Except for the ones from `/tiles`; i still want to get to that once we sort out uploads if you have time)
Were there any nginx log lines corresponding to trying the larger one?

**Rudo**
i tried to run the above cmd but nothing really shows up. the browser msg's right away that it's too large

**Seth**
New idea: can you paste the output from `nginx -T`?
(It'll be the config that _nginx_ thinks it has, not just the one we think it has)

**Rudo**
-T is invalid option

**Seth**
`nginx -t` then
Our nginx is too old :disappointed:

**Rudo**
Haha ok.
```
root@posm:~# nginx -t
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
```

**Seth**
`ls -l /etc/nginx/sites-enabled/00-posm`
`md5sum /etc/nginx/sites-enabled/00-posm`

**Rudo**
In that file there is a types_hash_max_size 2048 not sure if relevant

**Seth**
That looks separate


**Rudo**
```
root@posm:/etc/nginx# ls -l /etc/nginx/sites-enabled/00-posm
lrwxrwxrwx 1 root root 23 Apr  4 06:23 /etc/nginx/sites-enabled/00-posm -> ../sites-available/posm
```
```
root@posm:/etc/nginx# md5sum /etc/nginx/sites-enabled/00-posm
af8ea069203283e40cbcae134f7c6a7d  /etc/nginx/sites-enabled/00-posm
```

**Seth**
`md5sum /etc/nginx/sites-available/posm`
(Does that include the corrected upload limit? there are symlinks involved, so something may not be what we think it is)

**Rudo**
```
root@posm:/etc/nginx/sites-available# md5sum /etc/nginx/sites-available/posm
af8ea069203283e40cbcae134f7c6a7d  /etc/nginx/sites-available/posm
```
yup

**Seth**
I'm at a loss (and need to go shortly). I'll see if i can reproduce that later on...
Meanwhile, the other tiles problem...
`/var/log/upstart/tessera.log` should include an error message (while it's trying to start up)

**Rudo**
alright. i'll keep poking around also. thanks very much for your time on this, it's for sure appreciated

**Seth**
Sorry we can't figure it out right now...  It's frustrating that it worked for a while and then stopped.

**Rudo**
tessera.log has various kinds of errors
`Error: Postgis Plugin: ERROR:  relation "planet_osm_polygon" does not exist`

**Seth**
Ah, that may be expected if you're not using the POSM w/ a POSM bundle

**Rudo**
```
[0mGET /tiles/south-suriname/south-suriname/11/705/997.png [32m200 [0m23.987 ms - 2532[0m
```

```
Error: Postgis Plugin: FATAL:  the database system is starting up
Connection string: ' dbname=gis user=gis connect_timeout=1'
 encountered during parsing of layer 'ne_10m_rivers_lake_centerlines_scale_rank' in Layer
   at Error (native)
[Wed Apr  4 19:55:56 2018] Starting: tessera
Listening at http://0.0.0.0:8082
```
i see, that is the case (we're not using POSM bundle)

**Seth**
Ok, i think that's a non-issue then
As long as your south-suriname tiles are displaying

**Rudo**
those would just be in OSM right?

**Seth**
Right
Oh, in FP too

**Rudo**
hmmm actually they used to show in OSM, and Field Papers also. now the tiles aren't working

**Seth**
`service tessera restart` _may_ fix that

**Rudo**
just something else interesting i'm noticing, not sure if related -- the WiFi signal it's giving is POSM 2 and it used to just be POSM

**Seth**
did someone rename it?
that doesn't sound related unless there are 2 in the room and we've been debugging the wrong one :wink:
it would explain why there aren't any error messages in the nginx logs though...

**Rudo**
tried the service command, didn't seem to do much
haha, there is for sure only one!
just weird that a 2 got appended out of nowhere


**Seth**
Yeah, for sure
Are there new errors in the tessera logs?

**Rudo**
not that i could tell no.
In Settings, the WPA was activated with name "POSM" but "POSM 2" was an unsecured network. i deactivated and reactivated again, and that led to the device setting up a secure "POSM" and no more POSM 2
same upload issue though

**Seth**
Weird

**Comment by danbjoseph** [comment]
**Seth**
I found the source of the limit:
https://github.com/enyo/dropzone/blob/v4.3.0/src/dropzone.coffee#L136
dropzone is used by react-dropzone-component which is used by posm-admin-ui
https://github.com/posm/posm/issues/329
Alas, there's no easy way to fix it directly on the POSM w/o patching posm-admin-ui, rebuilding, and copying the new static assets

**Rudo**
i see. so in order to fix this, we would essentially have to re-install the POSM after adjusting this in the dropzone files

**Seth**
It's a bit easier than that. The javascript assets can be copied into place after being built
i'll see if i can create an updated build this afternoon and point you to the files to copy into place
