### ISSUE TITLE
Pillow limitations Imagery API

### ISSUE THREAD

**Issue by DKersbergen** [posm/posm#338]
Would it be possible to lift the limitations of the Imagery API for ingesting larger sized images by changing or disabling the max img size in the Image.DecompressionBombWarning within Pillow? If so, where would I be able to find the Pillow module in the POSM install?

**Comment by mojodna** [comment]
Which limitations are you referring to? Are you running into a specific problem?

The current POSM ISO (`0.7.2`, but not `master`) has a 256MB limit on uploads (fixed in https://github.com/posm/posm-admin-ui/commit/c0a54f85c8ba0f4b7f3833259d3f57e66d92e480).

Otherwise, GDAL should be the limiting factor (it's not particularly limiting).

The Imagery API runs as a Docker container (`quay.io/mojodna/posm-imagery-api`), so you'd want to look in https://github.com/posm/posm-imagery-api and where Pillow is installed there.

**Comment by DKersbergen** [comment]
Thanks Seth, yeah we are running into troubles when uploading data. The files themselves are not particularly big, roughly 80mb. But when they open we run into errors. I'll post those as well

On 11 Jul 2018 02:17, Seth Fitzsimmons <notifications@github.com> wrote:

Which limitations are you referring to? Are you running into a specific problem?

The current POSM ISO (0.7.2, but not master) has a 256MB limit on uploads (fixed in posm/posm-admin-ui@c0a54f8<https://github.com/posm/posm-admin-ui/commit/c0a54f85c8ba0f4b7f3833259d3f57e66d92e480>).

Otherwise, GDAL should be the limiting factor (it's not particularly limiting).

The Imagery API runs as a Docker container (quay.io/mojodna/posm-imagery-api), so you'd want to look in https://github.com/posm/posm-imagery-api and where Pillow is installed there.

**Comment by mojodna** [comment]
Yes, please. If you're able to share the imagery, I can also do some testing locally (seth@mojodna.net to keep things private).

**Comment by DKersbergen** [comment]
Surprisingly this file worked now, but this seems to be the strange part of this error, it seems to happen on random files some times. However, I got it on another file now. 

First this error shows up `server responded with code 0`
And when I try again this error: `<html> <head><title>413 Request Entity Too Large</title></head> <body bgcolor="white"> <center><h1>413 Request Entity Too Large</h1></center> <hr><center>nginx/1.4.6 (Ubuntu)</center> </body> </html> `

The file is too large to attach, however can be downloaded here: http://oin-hotosm.s3.amazonaws.com/59e4e31623c8440011d7b341/0/585b8e92-d4f9-4494-b570-615b35baaa02.tif, via https://map.openaerialmap.org/

**Comment by mojodna** [comment]
Great, thanks. I'll see if I can reproduce with that.

Meanwhile, can you check `/etc/nginx/sites-enabled/00-posm` to see what `client_max_body_size` is set to?

I'm curious if this change made it onto your install:

https://github.com/posm/posm-build/blob/7f3ab2e96bdce6771a765fcc4352cbabd22b881e/kickstart/etc/nginx-posm.conf#L28

Are you running on a NUC (or similar) or cloud host?

**Comment by mojodna** [comment]
I'm not able to reproduce with the current configuration.

**Comment by mojodna** [comment]
You'll need to do 2 things once you've done a fresh install of 0.7.2:

```bash
# upgrade posm-admin to remove the 256MB limit
git clone --recursive --depth 1 -b dist https://github.com/posm/posm-admin-ui /opt/posm-www
```

Change/set `client_max_body_size 0;` in `/etc/nginx/sites-enables/00-posm` (within the `server { ... }` stanza) to remove the Nginx limit.

There will be an updated version of POSM within the next month that will address these.

**Comment by DKersbergen** [comment]
Thank you so much for all the support, we will try to do so with the tips you have given.
