### ISSUE TITLE
AOI data not showing in iD editor

### ISSUE THREAD

**Issue by danbjoseph** [posm/posm#342]
map tiles look good, but opening the editor doesn't show any of the data
<img width="1357" alt="screen shot 2018-09-19 at 2 34 32 pm" src="https://user-images.githubusercontent.com/4806884/45773974-c7f92b80-bc19-11e8-92c7-a5d2a9411796.png">
<img width="1360" alt="screen shot 2018-09-19 at 2 34 51 pm" src="https://user-images.githubusercontent.com/4806884/45773976-c9c2ef00-bc19-11e8-874e-4fe8acd9a730.png">

when you load another AOI, does it just push the new OSM data into the database on POSM? overwrite what's there? other? if the POSM OSM db has local edits to it what happens to them?
<img width="1167" alt="screen shot 2018-09-19 at 2 41 25 pm" src="https://user-images.githubusercontent.com/4806884/45774116-2b835900-bc1a-11e8-92b7-1761ea7dfc32.png">

**Comment by mojodna** [comment]
Thanks. 2 things going on there (`/api/user/0.6/user/details` being a 403 is fine):

* the POSM imagery updater doesn't appear to have run (that creates `/opt/posm-www/posm_imagery.json`)
* CGImap doesn't seem to have started

I'll need to see if I can reproduce these locally.

Which ISO did you install from?

**Comment by danbjoseph** [comment]
hmm, i think `superposm-0.8.0.iso`
should i do 0.8.1 and see if the issue persists?

**Comment by mojodna** [comment]
No, I can start there. There shouldn't have been anything different other than uncertainties in the build process between the 2 versions.

**Comment by danbjoseph** [comment]
- was using the POSM bundle from this export: 
https://export.hotosm.org/en/v3/exports/8b6cc98c-7f60-4cc1-848a-0c51edbb51d4/
- and this was the one that was loaded first on the box:
https://export.hotosm.org/v3/exports/21544d54-3905-4787-94ef-52139ec82fa5/

**Comment by mojodna** [comment]
@danbjoseph neither of those links are public; can you provide direct links to `bundle.tar.gz` for each?

**Comment by mojodna** [comment]
Fixes to related (but maybe not root) problems:

* https://github.com/posm/posm-build/commit/82c744c9abcc2292dbe9537814a667a0b6d0cb63
* https://github.com/posm/posm-build/commit/8b6a54121492ef839cbfd04de4e26a0786671fd5
* https://github.com/posm/posm-admin/commit/967e0ddcdf8d3c0e695a06b9fc90fb210d08efa2

**Comment by danbjoseph** [comment]
https://export.hotosm.org/downloads/c0124679-7aed-485b-88be-70952df7bf4b/grenada-bundle.tar.gz

https://export.hotosm.org/downloads/9db723f4-a709-4600-86e3-8a47c22a0c65/st-georges-grenada-bundle.tar.gz

Do these work?

>

**Comment by mojodna** [comment]
Osmosis could still be connected while performing replication, so https://github.com/posm/posm-admin/commit/1600cbab673f243eea0a8fd9fcd870c6d885bf13 is a cleaner way of disconnecting active users. (https://github.com/posm/posm-build/commit/1d90981045e0d529a5cb65d72f72621300e47ee2 removes `sudoers` rules that became unnecessary with this approach)
