### ISSUE TITLE
changing SSID doesn't work

### ISSUE THREAD

**Issue by danbjoseph** [posm/posm#346]
installed `superposm-0.8.2.iso` on an Intel NUC Skull Canyon. changed the SSID from "POSM" to "superPOSM" and the change persists in the input box after switching away from and back to the settings page (and also after a reboot) but the visible network name remains as "POSM"

same thing with `posm-0.8.2.iso` on a NUC5PPYH

changing the WPA Passphrase **does** work

**Comment by danbjoseph** [comment]
from @mojodna - when `ssh`'ed in try:
```
/opt/admin/posm-admin/scripts/root_change-ssid.sh superPOSM
```

**Comment by mojodna** [comment]
Fixed in https://github.com/posm/posm-admin/commit/0ca7579224e3a18dd23d2e86c3ef404df589571c

**Comment by danbjoseph** [comment]
🎉 seth always knows the answer!

**Comment by mojodna** [comment]
Drat for not catching it previously.
