### ISSUE TITLE
SSID change didn't persist after reboot

### ISSUE THREAD

**Issue by danbjoseph** [posm/posm#354]
I’ll have to see if the problem happens again. But I changed the SSID to “jordan” (there’s a Michael Jordan sticker on it) and after a reboot the broadcast SSID returned to “POSM” while the network settings still had “jordan” in the field when viewing the settings page.

<img width="342" alt="Screen Shot 2019-08-05 at 9 36 31 PM" src="https://user-images.githubusercontent.com/4806884/62541395-b4ea4c80-b827-11e9-8484-9dec0b42b4c6.png">
<img width="650" alt="Screen Shot 2019-08-05 at 9 36 26 PM" src="https://user-images.githubusercontent.com/4806884/62541400-b61b7980-b827-11e9-8d9e-db7b8e242d51.png">

**Comment by danbjoseph** [comment]
with install of `posm-auth-replay-tool-2020-April-17-2nd.iso` on an Intel NUC5PPYH 

set the SSID to `opengeo` and after a report the network name returned to `POSM` even though the SSID still read as `opengeo` at http://posm.io/posm/settings 

![Screen Shot 2020-05-05 at 4 16 21 PM](https://user-images.githubusercontent.com/4806884/81111987-efcefd00-8eeb-11ea-8d61-982c3985827a.png)

![Screen Shot 2020-05-05 at 4 16 28 PM](https://user-images.githubusercontent.com/4806884/81111988-f1002a00-8eeb-11ea-965b-5ac8ff52fb4d.png)

**Comment by bewakes** [comment]
@danbjoseph , seems like it is the problem with the network manager's display in your mac. The SSID seems to have changed.
I set the ssid to `__POSM__` and here it is in my phone:
![image](https://user-images.githubusercontent.com/5417640/84624626-77ebed80-af01-11ea-827f-c1eda5a1d72c.png)
And in my computer I use command line tool `wifi-menu` on which also the change got reflected.
![image](https://user-images.githubusercontent.com/5417640/84627208-31e55880-af06-11ea-9552-b9e2c968e0d8.png)

And here it is on the settings page:
![image](https://user-images.githubusercontent.com/5417640/84627757-2b0b1580-af07-11ea-8cf3-64ec1355e38b.png)

**Comment by danbjoseph** [comment]
and after a reboot of the POSM device, its network was still named `__POSM__`?

**Comment by bewakes** [comment]
oops, my bad. Didn't check after rebooting. Yes, the SSID did not change.

**Comment by bewakes** [comment]
So, the issue was that whenever posm rebooted, it seems to reload the config from `/root/posm-build/kickstart/etc` instead from `/etc`. Changing this behaviour seemed a bit risky so I came up with this workaround: https://github.com/posm/posm-admin/pull/21/files#diff-7d2b62b1d855de8aed6c513918ed27a2R18-R26
This also changes the contents inside `/root/posm-build/kickstart/etc`. Let me know if this is not okay.

**Comment by danbjoseph** [comment]
are there other things that load from `/root/posm-build/kickstart/etc`? are those files/folders generally the initial code? do other processes use the files there instead of in `/etc`?
