### ISSUE TITLE
/etc/hosts isn't written currently during installation

### ISSUE THREAD

**Issue by mojodna** [posm/posm#357]
The templated version is overwritten somehow. This doesn't affect most things, but it does prevent Field Papers atlases from being generated, as looking up `posm.io` doesn't resolve correctly from the POSM itself.

I'm planning to take a look at this early next week.

**Comment by danbjoseph** [comment]
this is still an issue, right?

**Comment by mojodna** [comment]
It’s fixed and I think it made it into the latest release build I made.

**Comment by danbjoseph** [comment]
thank you!
