### ISSUE TITLE
Missing 

### ISSUE THREAD

**Issue by acraiga** [posm/posm#361]
I'm new to POSM. I've been arguing with it a bit, and saw the permissions problem listed in the previous question, but I got around it. But this next one is not easy to get around.

I'm running POSM under VirtualBox 6.0, on a MacBookPro with 16GB of RAM running MacOS 10.15.4. POSM is 0.9.1. The VM has 8GB of RAM assigned. I'm just experimenting with POSM at this point so I can start over at any point if you need me to.

When I go to http://VM-Host/posm-admin/pages/deployment/aoi-deploy/, I can enter the HOTOSM Export AOI URL and it works, until it hits the permissions problem. Then I restart the AOI deployment (after fixing the permissions) and I then get this problem:

Osm2pgsql took 165s overall

==> /opt/admin/posm-admin/scripts/gis_render-db-pbf2render.sh: END

==> tessera-fp-reset.js
       manifest path: /opt/data/aoi/SantaClaraCo/manifest.json

/opt/admin/posm-admin/scripts/tessera-fp-reset.js:66
                if (properties.type.toLowerCase().indexOf('mbtiles') > -1) {
                                    ^

TypeError: Cannot read property 'toLowerCase' of undefined
    at /opt/admin/posm-admin/scripts/tessera-fp-reset.js:66:37
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)

false

Any suggestions would be greatly appreciated. Or steps to debug.
Thanks!

PS. I restarted the AOI Deployment again and it passed the previous error point with no problem, but I'm beginning to doubt the veracity of the data at this point. But we'll see when I get there.

**Comment by acraiga** [comment]
Actually, it didn't get past the above error message, it just took a while to get there.

Completed planet_osm_polygon
node cache: stored: 7776973(100.00%), storage efficiency: 51.87% (dense blocks: 206, sparse nodes: 6652252), hit rate: 100.00%

Osm2pgsql took 9334s overall

==> /opt/admin/posm-admin/scripts/gis_render-db-pbf2render.sh: END

==> tessera-fp-reset.js
       manifest path: /opt/data/aoi/SantaClaraCo/manifest.json

/opt/admin/posm-admin/scripts/tessera-fp-reset.js:66
                if (properties.type.toLowerCase().indexOf('mbtiles') > -1) {
                                    ^

TypeError: Cannot read property 'toLowerCase' of undefined
    at /opt/admin/posm-admin/scripts/tessera-fp-reset.js:66:37
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
false

**Comment by danbjoseph** [comment]
Hi! We're always excited to see more people experimenting with the software. Sorry you ran into trouble with it. You said you were able to get past the problem described in #360 ? Did you do something to get past it, or it just didn't occur in your instance?

**Comment by acraiga** [comment]
Hello,
	Yes, I ran into the same problem as in #360 and was able to find the file permissions problem, and change the permissions from 600 to 644. Then I restarted the AOI and it continued on. That’s when I ran into the problem in #361. Do you need the name of the file with the permissions problem from #360?

**Comment by bewakes** [comment]
It seems like the manifest json in the exported tar.gz has inconsistencies in attributes. As in the following json, we can see there are two attributes `type` and `Type` referring to `type`. So, the js code fails at that point.
```{
  "title": "Jawalakhel",
  "name": "Jawalakhel",
  "description": "Map of jawalakhel",
  "bbox": [
    85.31066555023207,
    27.67117097577173,
    85.32710212707534,
    27.682648488328013
  ],
  "contents": {
    "navigation/Osmand_2.obf": {
      "Type": "OsmAnd"
    },
    "tiles/Jawalakhel.mbtiles": {
      "type": "MBTiles",
      "minzoom": 5,
      "maxzoom": 15,
      "source": "http://tile.openstreetmap.org/{z}/{x}/{y}.png"
    },
    "osm/overpass.osm.pbf": {
      "Type": "OSM/PBF"
    }
  }
}
```
Updating the code to check for both the types should fix this.
